/** Listas cerradas de los formularios de publicación. */

// Las 16 regiones, de norte a sur: el orden geográfico es el que espera un
// chileno en un select, no el alfabético.
export const REGIONES = [
  'Arica y Parinacota',
  'Tarapacá',
  'Antofagasta',
  'Atacama',
  'Coquimbo',
  'Valparaíso',
  'Metropolitana',
  "O'Higgins",
  'Maule',
  'Ñuble',
  'Biobío',
  'La Araucanía',
  'Los Ríos',
  'Los Lagos',
  'Aysén',
  'Magallanes',
] as const;

export type Region = (typeof REGIONES)[number];

// Las 346 comunas de Chile, agrupadas por región. El <select> las renderiza
// enteras en <optgroup> —así funciona sin JavaScript— y `CamposUbicacion` deja
// a la vista solo el grupo de la región elegida. Ningún nombre se repite entre
// regiones, de ahí que el par región/comuna sea verificable.
export const COMUNAS_POR_REGION: Record<Region, readonly string[]> = {
  'Arica y Parinacota': ['Arica', 'Camarones', 'Putre', 'General Lagos'],
  Tarapacá: ['Iquique', 'Alto Hospicio', 'Pozo Almonte', 'Camiña', 'Colchane', 'Huara', 'Pica'],
  Antofagasta: [
    'Antofagasta',
    'Mejillones',
    'Sierra Gorda',
    'Taltal',
    'Calama',
    'Ollagüe',
    'San Pedro de Atacama',
    'Tocopilla',
    'María Elena',
  ],
  Atacama: [
    'Copiapó',
    'Caldera',
    'Tierra Amarilla',
    'Chañaral',
    'Diego de Almagro',
    'Vallenar',
    'Alto del Carmen',
    'Freirina',
    'Huasco',
  ],
  Coquimbo: [
    'La Serena',
    'Coquimbo',
    'Andacollo',
    'La Higuera',
    'Paiguano',
    'Vicuña',
    'Illapel',
    'Canela',
    'Los Vilos',
    'Salamanca',
    'Ovalle',
    'Combarbalá',
    'Monte Patria',
    'Punitaqui',
    'Río Hurtado',
  ],
  Valparaíso: [
    'Valparaíso',
    'Casablanca',
    'Concón',
    'Juan Fernández',
    'Puchuncaví',
    'Quintero',
    'Viña del Mar',
    'Isla de Pascua',
    'Los Andes',
    'Calle Larga',
    'Rinconada',
    'San Esteban',
    'La Ligua',
    'Cabildo',
    'Papudo',
    'Petorca',
    'Zapallar',
    'Quillota',
    'Calera',
    'Hijuelas',
    'La Cruz',
    'Nogales',
    'San Antonio',
    'Algarrobo',
    'Cartagena',
    'El Quisco',
    'El Tabo',
    'Santo Domingo',
    'San Felipe',
    'Catemu',
    'Llaillay',
    'Panquehue',
    'Putaendo',
    'Santa María',
    'Quilpué',
    'Limache',
    'Olmué',
    'Villa Alemana',
  ],
  Metropolitana: [
    'Santiago',
    'Cerrillos',
    'Cerro Navia',
    'Conchalí',
    'El Bosque',
    'Estación Central',
    'Huechuraba',
    'Independencia',
    'La Cisterna',
    'La Florida',
    'La Granja',
    'La Pintana',
    'La Reina',
    'Las Condes',
    'Lo Barnechea',
    'Lo Espejo',
    'Lo Prado',
    'Macul',
    'Maipú',
    'Ñuñoa',
    'Pedro Aguirre Cerda',
    'Peñalolén',
    'Providencia',
    'Pudahuel',
    'Quilicura',
    'Quinta Normal',
    'Recoleta',
    'Renca',
    'San Joaquín',
    'San Miguel',
    'San Ramón',
    'Vitacura',
    'Puente Alto',
    'Pirque',
    'San José de Maipo',
    'Colina',
    'Lampa',
    'Til Til',
    'San Bernardo',
    'Buin',
    'Paine',
    'Calera de Tango',
    'Melipilla',
    'Alhué',
    'Curacaví',
    'María Pinto',
    'San Pedro',
    'Talagante',
    'El Monte',
    'Isla de Maipo',
    'Padre Hurtado',
    'Peñaflor',
  ],
  "O'Higgins": [
    'Rancagua',
    'Codegua',
    'Coinco',
    'Coltauco',
    'Doñihue',
    'Graneros',
    'Las Cabras',
    'Machalí',
    'Malloa',
    'Mostazal',
    'Olivar',
    'Peumo',
    'Pichidegua',
    'Quinta de Tilcoco',
    'Rengo',
    'Requínoa',
    'San Vicente',
    'Pichilemu',
    'La Estrella',
    'Litueche',
    'Marchihue',
    'Navidad',
    'Paredones',
    'San Fernando',
    'Chépica',
    'Chimbarongo',
    'Lolol',
    'Nancagua',
    'Palmilla',
    'Peralillo',
    'Placilla',
    'Pumanque',
    'Santa Cruz',
  ],
  Maule: [
    'Curicó',
    'Hualañé',
    'Licantén',
    'Molina',
    'Rauco',
    'Romeral',
    'Sagrada Familia',
    'Teno',
    'Vichuquén',
    'Talca',
    'Constitución',
    'Curepto',
    'Empedrado',
    'Maule',
    'Pelarco',
    'Pencahue',
    'Río Claro',
    'San Clemente',
    'San Rafael',
    'Linares',
    'Colbún',
    'Longaví',
    'Parral',
    'Retiro',
    'San Javier',
    'Villa Alegre',
    'Yerbas Buenas',
    'Cauquenes',
    'Chanco',
    'Pelluhue',
  ],
  Ñuble: [
    'Chillán',
    'Bulnes',
    'Chillán Viejo',
    'El Carmen',
    'Pemuco',
    'Pinto',
    'Quillón',
    'San Ignacio',
    'Yungay',
    'San Carlos',
    'Coihueco',
    'Ñiquén',
    'San Fabián',
    'San Nicolás',
    'Quirihue',
    'Cobquecura',
    'Coelemu',
    'Ninhue',
    'Portezuelo',
    'Ránquil',
    'Trehuaco',
  ],
  Biobío: [
    'Concepción',
    'Coronel',
    'Chiguayante',
    'Florida',
    'Hualqui',
    'Lota',
    'Penco',
    'San Pedro de la Paz',
    'Santa Juana',
    'Talcahuano',
    'Tomé',
    'Hualpén',
    'Lebu',
    'Arauco',
    'Cañete',
    'Contulmo',
    'Curanilahue',
    'Los Álamos',
    'Tirúa',
    'Los Ángeles',
    'Antuco',
    'Cabrero',
    'Laja',
    'Mulchén',
    'Nacimiento',
    'Negrete',
    'Quilaco',
    'Quilleco',
    'San Rosendo',
    'Santa Bárbara',
    'Tucapel',
    'Yumbel',
    'Alto Biobío',
  ],
  'La Araucanía': [
    'Temuco',
    'Carahue',
    'Cholchol',
    'Curarrehue',
    'Freire',
    'Galvarino',
    'Gorbea',
    'Lautaro',
    'Loncoche',
    'Melipeuco',
    'Nueva Imperial',
    'Padre Las Casas',
    'Perquenco',
    'Pitrufquén',
    'Pucón',
    'Saavedra',
    'Teodoro Schmidt',
    'Toltén',
    'Vilcún',
    'Villarrica',
    'Cunco',
    'Angol',
    'Collipulli',
    'Curacautín',
    'Ercilla',
    'Lonquimay',
    'Los Sauces',
    'Lumaco',
    'Purén',
    'Renaico',
    'Traiguén',
    'Victoria',
  ],
  'Los Ríos': [
    'Valdivia',
    'Corral',
    'Lanco',
    'Los Lagos',
    'Máfil',
    'Mariquina',
    'Paillaco',
    'Panguipulli',
    'La Unión',
    'Futrono',
    'Lago Ranco',
    'Río Bueno',
  ],
  'Los Lagos': [
    'Puerto Montt',
    'Calbuco',
    'Cochamó',
    'Fresia',
    'Frutillar',
    'Los Muermos',
    'Llanquihue',
    'Maullín',
    'Puerto Varas',
    'Osorno',
    'Puerto Octay',
    'Purranque',
    'Puyehue',
    'Río Negro',
    'San Juan de la Costa',
    'San Pablo',
    'Castro',
    'Ancud',
    'Chonchi',
    'Curaco de Vélez',
    'Dalcahue',
    'Puqueldón',
    'Queilén',
    'Quellón',
    'Quemchi',
    'Quinchao',
    'Chaitén',
    'Futaleufú',
    'Hualaihué',
    'Palena',
  ],
  Aysén: [
    'Coyhaique',
    'Lago Verde',
    'Aysén',
    'Cisnes',
    'Guaitecas',
    'Chile Chico',
    'Río Ibáñez',
    'Cochrane',
    "O'Higgins",
    'Tortel',
  ],
  Magallanes: [
    'Punta Arenas',
    'Laguna Blanca',
    'Río Verde',
    'San Gregorio',
    'Cabo de Hornos',
    'Antártica',
    'Porvenir',
    'Primavera',
    'Timaukel',
    'Natales',
    'Torres del Paine',
  ],
};

/**
 * `true` solo si la comuna pertenece a esa región. El par llega del cliente, que
 * puede mandar cualquier cosa: `region` se busca como clave propia porque
 * `COMUNAS_POR_REGION['toString']` existe en el prototipo y devolvería función.
 */
export function comunaEnRegion(region: string, comuna: string): boolean {
  return Object.hasOwn(COMUNAS_POR_REGION, region) && COMUNAS_POR_REGION[region as Region].includes(comuna);
}

export const COMBUSTIBLES = ['Bencina', 'Diésel', 'Híbrido', 'Eléctrico', 'Gas'] as const;

export const TRANSMISIONES = ['Manual', 'Automática'] as const;

export const TRACCIONES = ['4x4', 'Delantera', 'Trasera'] as const;

export const ESTADOS_AVISO = ['publicado', 'pausado', 'vendido'] as const;
export type EstadoAviso = (typeof ESTADOS_AVISO)[number];

export const ETIQUETA_ESTADO: Record<EstadoAviso, string> = {
  publicado: 'Publicado',
  pausado: 'Pausado',
  vendido: 'Vendido',
};

export const MOTIVOS_REPORTE = [
  'No es un auto',
  'Precio o datos falsos',
  'Estafa o fraude',
  'Contenido ofensivo',
  'Aviso duplicado',
  'Otro',
] as const;

// Ciclo de vida de un reporte en la bandeja de moderación: se resuelve cuando el
// aviso se despublica, y se descarta cuando el reporte no procede.
export const ESTADOS_REPORTE = ['pendiente', 'resuelto', 'descartado'] as const;
export type EstadoReporte = (typeof ESTADOS_REPORTE)[number];

export const ETIQUETA_REPORTE: Record<EstadoReporte, string> = {
  pendiente: 'Pendiente',
  resuelto: 'Resuelto',
  descartado: 'Descartado',
};

/** El año del auto: se admite el modelo del año siguiente, que ya se vende. */
export const ANIO_MINIMO = 1950;
export const anioMaximo = () => new Date().getFullYear() + 1;
